create table hrms_dept_tbl_lkup_v (
SETID CHAR(5),
ORG_NODE CHAR(10),
EFF_DT timestamp,
EFF_STATUS CHAR(1),
DESCR CHAR(30),
DESCRSHORT CHAR(10),
COMPANY CHAR(3),
SETID_LOCATION CHAR(5),
TAX_LOCATION_CD CHAR(10),
DW_LOAD_DT timestamp);

create table bair_organization_lookup (
ORG_CODE CHAR(5),
ORG_DESC CHAR(30),
PROCESSING_UNIT_ID CHAR(10),
PROCESSING_UNIT_DESC CHAR(30),
ORG_L2_CONTROL_UNIT_NODE CHAR(20),
ORG_L2_CONTROL_UNIT_DESC CHAR(30),
ORG_L3_DIVISION_NODE CHAR(20),
ORG_L3_DIVISION_DESC CHAR(30),
ORG_L4_DEPARTMENT_NODE CHAR(20),
ORG_L4_DEPARTMENT_DESC CHAR(30),
ORG_L5_DISCIPLINE_GROUP_NODE CHAR(20),
ORG_L5_DISCIPLINE_GROUP_DESC CHAR(30),
ORG_L6_SUB_UNIT_NODE CHAR(20),
ORG_L6_SUB_UNIT_DESC CHAR(30),
DEPTID CHAR(5));
